import Footer from "@/components/Footer";
import Header from "@/components/Navbar";
import ReactQueryProvider from "@/components/providers/ReactQuery";
// import { ThemeProvider } from "@/components/providers/theme";
import type { Metadata } from "next";
import { NextIntlClientProvider } from "next-intl";
import { getLocale, getMessages } from "next-intl/server";
import localFont from "next/font/local";
import { Toaster } from "sonner";
import "./globals.css";

const geistMono = localFont({
    src: "./fonts/GeistMonoVF.woff",
    variable: "--font-geist-mono",
    weight: "100 900",
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default async function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    const locale = await getLocale();

    // Providing all messages to the client
    // side is the easiest way to get started
    const messages = await getMessages();
    return (
        <html suppressHydrationWarning lang={locale}>
            <body
                suppressHydrationWarning
                className={` ${geistMono.variable} antialiased`}
            >
                {/* <ThemeProvider
                    attribute="class"
                    defaultTheme="light"
                    enableSystem
                    disableTransitionOnChange
                > */}
                <NextIntlClientProvider messages={messages}>
                    <Toaster />
                    <ReactQueryProvider>
                        <Header />
                        {children}
                        <Footer />
                    </ReactQueryProvider>
                </NextIntlClientProvider>
                {/* </ThemeProvider> */}
            </body>
        </html>
    );
}
